on:
  push:
    branches:
      - master

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/209318686550/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@practice-377017.iam.gserviceaccount.com'

    - name: Upload file to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        source_file: "sqlscripts/table.sql"
        destination: "gs://my-bucket/table.sql"
    