name: Upload file to Google Cloud Storage

on:
  push:
    branches:
      - main

env:
  ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}

jobs:
  upload_to_gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google
      uses: google-github-actions/auth@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}

    - name: Upload file to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: '/OZShubham/cloudbuild-terraform/sqlscripts/table.sql'
        destination: 'bucket-shu/table.sql'
