on:
  push:
    branches:
      - master

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/209318686550/locations/global/workloadIdentityPools/mypool/providers/my-provider'
        service_account: 'my-122@practice-377017.iam.gserviceaccount.com'

    - id: 'upload'
      name: Upload file to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: "./sqlscripts"
        destination: "bucket-shu" 
    